config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :monsters
  resources :character_attributes
  resources :characters
  resources :character_classes

  root to: 'home#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/character.rb
# frozen_string_literal: true

class Character < ApplicationRecord
  belongs_to :character_class
  belongs_to :character_attribute
end

app/controllers/characters_controller.rb
# frozen_string_literal: true

class CharactersController < ApplicationController
  before_action :set_character, only: %i[show edit update destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show; end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit; end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_character
    @character = Character.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def character_params
    params.require(:character).permit(:name, :level, :hp, :mp, :gold, :character_class_id)
  end
end

app/helpers/characters_helper.rb
# frozen_string_literal: true

module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character, local: true) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level %>
  </div>

  <div class="field">
    <%= form.label :hp %>
    <%= form.text_field :hp %>
  </div>

  <div class="field">
    <%= form.label :mp %>
    <%= form.text_field :mp %>
  </div>

  <div class="field">
    <%= form.label :gold %>
    <%= form.number_field :gold %>
  </div>

  <div class="field">
    <%= form.label :character_class_id %>
    <%= form.text_field :character_class_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/_show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <%= image_tag("knight2.jpg",  width: "240") %>

  <div class='attributes' style='float: left;'>
    <p>
      <strong>Name:</strong>
      <%= @character.name %>
    </p>

    <p>
      <strong>Level:</strong>
      <%= @character.level %>
    </p>

    <p>
      <strong>Hp:</strong>
      <%= @character.hp %>
    </p>

    <p>
      <strong>Mp:</strong>
      <%= @character.mp %>
    </p>

    <p>
      <strong>Gold:</strong>
      <%= @character.gold %>
    </p>

    <p>
      <strong>Class:</strong>
      <%= @character.character_class.name %>
    </p>
  </div>
</div>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Characters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Hp</th>
      <th>Mp</th>
      <th>Gold</th>
      <th>Character class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.level %></td>
        <td><%= character.hp %></td>
        <td><%= character.mp %></td>
        <td><%= character.gold %></td>
        <td><%= character.character_class %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @character.level %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @character.hp %>
</p>

<p>
  <strong>Mp:</strong>
  <%= @character.mp %>
</p>

<p>
  <strong>Gold:</strong>
  <%= @character.gold %>
</p>

<p>
  <strong>Class:</strong>
  <%= @character.character_class.name %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>