config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :monsters
  resources :character_attributes
  resources :characters
  resources :character_classes

  root to: 'home#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/character_classes_controller.rb
# frozen_string_literal: true

class CharacterClassesController < ApplicationController
  before_action :set_character_class, only: %i[show edit update destroy]

  # GET /character_classes
  # GET /character_classes.json
  def index
    @character_classes = CharacterClass.all
  end

  # GET /character_classes/1
  # GET /character_classes/1.json
  def show; end

  # GET /character_classes/new
  def new
    @character_class = CharacterClass.new
  end

  # GET /character_classes/1/edit
  def edit; end

  # POST /character_classes
  # POST /character_classes.json
  def create
    @character_class = CharacterClass.new(character_class_params)

    respond_to do |format|
      if @character_class.save
        format.html { redirect_to @character_class, notice: 'Character class was successfully created.' }
        format.json { render :show, status: :created, location: @character_class }
      else
        format.html { render :new }
        format.json { render json: @character_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /character_classes/1
  # PATCH/PUT /character_classes/1.json
  def update
    respond_to do |format|
      if @character_class.update(character_class_params)
        format.html { redirect_to @character_class, notice: 'Character class was successfully updated.' }
        format.json { render :show, status: :ok, location: @character_class }
      else
        format.html { render :edit }
        format.json { render json: @character_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /character_classes/1
  # DELETE /character_classes/1.json
  def destroy
    @character_class.destroy
    respond_to do |format|
      format.html { redirect_to character_classes_url, notice: 'Character class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_character_class
    @character_class = CharacterClass.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def character_class_params
    params.require(:character_class).permit(:name, :description)
  end
end

app/helpers/character_classes_helper.rb
# frozen_string_literal: true

module CharacterClassesHelper
end

app/views/character_classes/_form.html.erb
<%= form_with(model: character_class, local: true) do |form| %>
  <% if character_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character_class.errors.count, "error") %> prohibited this character_class from being saved:</h2>

      <ul>
      <% character_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/character_classes/edit.html.erb
<h1>Editing Character Class</h1>

<%= render 'form', character_class: @character_class %>

<%= link_to 'Show', @character_class %> |
<%= link_to 'Back', character_classes_path %>

app/views/character_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Character Classes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @character_classes.each do |character_class| %>
      <tr>
        <td><%= character_class.name %></td>
        <td><%= character_class.description %></td>
        <td><%= link_to 'Show', character_class %></td>
        <td><%= link_to 'Edit', edit_character_class_path(character_class) %></td>
        <td><%= link_to 'Destroy', character_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character Class', new_character_class_path %>

app/views/character_classes/new.html.erb
<h1>New Character Class</h1>

<%= render 'form', character_class: @character_class %>

<%= link_to 'Back', character_classes_path %>

app/views/character_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character_class.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @character_class.description %>
</p>

<%= link_to 'Edit', edit_character_class_path(@character_class) %> |
<%= link_to 'Back', character_classes_path %>